### ISSUE TITLE
Home Page designing

### ISSUE THREAD

**Issue by raulamit** [raulamit/NewsSummarizerAngular#1]
Tasks
* Add text describing the product
* Add more news slides
* Add Summaries for the existing slides

Links for existing Slides
- [Trump](https://www.theguardian.com/us-news/2018/jun/19/trump-backs-plan-to-end-family-separations-but-shirks-responsibility)
- [basketball](https://www.theguardian.com/sport/2018/jun/20/dwight-howard-trade-brooklyn-nets)
- [Ronaldo](https://www.theguardian.com/football/2018/jun/20/portugal-morocco-world-cup-group-b-match-report)
- [Probiotics](https://www.theguardian.com/science/2018/jun/20/no-clear-evidence-probiotics-can-help-with-human-anxiety-study-finds)

**Comment by mohitebhushan** [comment]
Done.

**Comment by raulamit** [comment]
We are missing text describing the product, a marketing text. Ideally, it should be above explore. How about "Stay informed with news summaries". Should be bold and font size should be big enough.
